import "./globals.css";
import { Atkinson_Hyperlegible } from "next/font/google";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Atkinson_Hyperlegible({
  weight: ["400", "700"],
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
