import Link from "next/link";

export const metadata = {
  title: "Todo App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-slate-100 min-h-screen flex flex-col">
      <nav className="sticky top-0 text-center p-5 text-4xl font-bold">
        <Link href="/todo">Todo</Link>
      </nav>
      <main className="p-5">{children}</main>
    </div>
  );
}
